# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/titico03/Documents/PogLang

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/titico03/Documents/PogLang

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/titico03/Documents/PogLang/CMakeFiles /home/titico03/Documents/PogLang//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/titico03/Documents/PogLang/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gamer

# Build rule for target.
gamer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gamer
.PHONY : gamer

# fast build rule for target.
gamer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamer.dir/build.make CMakeFiles/gamer.dir/build
.PHONY : gamer/fast

#=============================================================================
# Target rules for targets named PogLang

# Build rule for target.
PogLang: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PogLang
.PHONY : PogLang

# fast build rule for target.
PogLang/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PogLang.dir/build.make CMakeFiles/PogLang.dir/build
.PHONY : PogLang/fast

#=============================================================================
# Target rules for targets named gamer_testtwo

# Build rule for target.
gamer_testtwo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gamer_testtwo
.PHONY : gamer_testtwo

# fast build rule for target.
gamer_testtwo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamer_testtwo.dir/build.make CMakeFiles/gamer_testtwo.dir/build
.PHONY : gamer_testtwo/fast

#=============================================================================
# Target rules for targets named gamer_test

# Build rule for target.
gamer_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gamer_test
.PHONY : gamer_test

# fast build rule for target.
gamer_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamer_test.dir/build.make CMakeFiles/gamer_test.dir/build
.PHONY : gamer_test/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PogLang.dir/build.make CMakeFiles/PogLang.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PogLang.dir/build.make CMakeFiles/PogLang.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PogLang.dir/build.make CMakeFiles/PogLang.dir/main.cpp.s
.PHONY : main.cpp.s

src/gamer/gamer.o: src/gamer/gamer.cpp.o
.PHONY : src/gamer/gamer.o

# target to build an object file
src/gamer/gamer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamer.dir/build.make CMakeFiles/gamer.dir/src/gamer/gamer.cpp.o
.PHONY : src/gamer/gamer.cpp.o

src/gamer/gamer.i: src/gamer/gamer.cpp.i
.PHONY : src/gamer/gamer.i

# target to preprocess a source file
src/gamer/gamer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamer.dir/build.make CMakeFiles/gamer.dir/src/gamer/gamer.cpp.i
.PHONY : src/gamer/gamer.cpp.i

src/gamer/gamer.s: src/gamer/gamer.cpp.s
.PHONY : src/gamer/gamer.s

# target to generate assembly for a file
src/gamer/gamer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamer.dir/build.make CMakeFiles/gamer.dir/src/gamer/gamer.cpp.s
.PHONY : src/gamer/gamer.cpp.s

test/gamer/gamer_test.o: test/gamer/gamer_test.cpp.o
.PHONY : test/gamer/gamer_test.o

# target to build an object file
test/gamer/gamer_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamer_test.dir/build.make CMakeFiles/gamer_test.dir/test/gamer/gamer_test.cpp.o
.PHONY : test/gamer/gamer_test.cpp.o

test/gamer/gamer_test.i: test/gamer/gamer_test.cpp.i
.PHONY : test/gamer/gamer_test.i

# target to preprocess a source file
test/gamer/gamer_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamer_test.dir/build.make CMakeFiles/gamer_test.dir/test/gamer/gamer_test.cpp.i
.PHONY : test/gamer/gamer_test.cpp.i

test/gamer/gamer_test.s: test/gamer/gamer_test.cpp.s
.PHONY : test/gamer/gamer_test.s

# target to generate assembly for a file
test/gamer/gamer_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamer_test.dir/build.make CMakeFiles/gamer_test.dir/test/gamer/gamer_test.cpp.s
.PHONY : test/gamer/gamer_test.cpp.s

test/gamertwo/gamer_testtwo.o: test/gamertwo/gamer_testtwo.cpp.o
.PHONY : test/gamertwo/gamer_testtwo.o

# target to build an object file
test/gamertwo/gamer_testtwo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamer_testtwo.dir/build.make CMakeFiles/gamer_testtwo.dir/test/gamertwo/gamer_testtwo.cpp.o
.PHONY : test/gamertwo/gamer_testtwo.cpp.o

test/gamertwo/gamer_testtwo.i: test/gamertwo/gamer_testtwo.cpp.i
.PHONY : test/gamertwo/gamer_testtwo.i

# target to preprocess a source file
test/gamertwo/gamer_testtwo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamer_testtwo.dir/build.make CMakeFiles/gamer_testtwo.dir/test/gamertwo/gamer_testtwo.cpp.i
.PHONY : test/gamertwo/gamer_testtwo.cpp.i

test/gamertwo/gamer_testtwo.s: test/gamertwo/gamer_testtwo.cpp.s
.PHONY : test/gamertwo/gamer_testtwo.s

# target to generate assembly for a file
test/gamertwo/gamer_testtwo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gamer_testtwo.dir/build.make CMakeFiles/gamer_testtwo.dir/test/gamertwo/gamer_testtwo.cpp.s
.PHONY : test/gamertwo/gamer_testtwo.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... PogLang"
	@echo "... gamer"
	@echo "... gamer_test"
	@echo "... gamer_testtwo"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/gamer/gamer.o"
	@echo "... src/gamer/gamer.i"
	@echo "... src/gamer/gamer.s"
	@echo "... test/gamer/gamer_test.o"
	@echo "... test/gamer/gamer_test.i"
	@echo "... test/gamer/gamer_test.s"
	@echo "... test/gamertwo/gamer_testtwo.o"
	@echo "... test/gamertwo/gamer_testtwo.i"
	@echo "... test/gamertwo/gamer_testtwo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

